### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cjhanson** [Brayden/UICheckbox#1]
In the comments headers it says all rights reserved and no permissive use license such as MIT etc... If you do intend this to be open source and usable by people please specify how you are allowing it to be used.

**Comment by hidefguy** [comment]
Wish I'd read this before downloading  - as written , this project is unusable for most people because there's no license granted.

**Comment by Brayden** [comment]
@cjhanson @hidefguy  Sorry about that.  I'll put an update out that reflects it as open source license for anyone to use and modify to their hearts desire.

**Comment by Brayden** [comment]
License has been added to the README
