### ISSUE TITLE
non-ARC, or classic memory management, support

### ISSUE THREAD

**Issue by dautermann** [Brayden/UICheckbox#3]
I'm super comfortable with ARC myself, but I'm working with another old skool developer who just isn't ready to take the plunge into Automated Reference Counting (he says "I'd rather manage objects _myself_").

In order to make UICheckbox useful for these luddites, it might be nice to consider adding in some lines that look like this:

``` objective-c
Index: UICheckbox.m
===================================================================
--- UICheckbox.m    (revision 72)
+++ UICheckbox.m    (working copy)
@@ -28,6 +28,14 @@
 @synthesize text = _text;
 @synthesize textLabel = _textLabel;

+#if !__has_feature(objc_arc)
+-(void)dealloc
+{
+   [_text release];
+   [super dealloc];
+}
+#endif
+
 -(void)awakeFromNib {
     self.backgroundColor = [UIColor clearColor];
 }
@@ -84,7 +92,11 @@
 }

 -(void)setText:(NSString *)stringValue {
+#if __has_feature(objc_arc)
     _text = stringValue;
+#else
+    _text = [stringValue retain];
+#endif
     [self setNeedsDisplay];
 }
```

**Comment by Brayden** [comment]
@dautermann Fixed https://github.com/Brayden/UICheckbox/commit/b3d7edd850d0107c3cbae7b4097f584f33bc056e

Thanks for your contributions!
